spring:
  application:
    name: gohub


  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: root
    password: pass@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port:8080
